project:
  type: book
  output-dir: ../docs

book:
  title: "Mini-COES Huelgas"
  author: "Pablo Pérez, Kevin Carrasco, Daniela Olivares"
  date: "05-19-2025"
  chapters:
    - index.qmd
    - 01-procesamiento.qmd
    - 02-descriptivo.qmd
    - 03-regresiones.qmd
    - 04-cross-lagged.qmd
    - 05-graphs.qmd
    # - summary.qmd
    # - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



